CREATE SCHEMA "Arcadia";

CREATE TABLE "follows" (
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp
);

CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "username" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" integer PRIMARY KEY,
  "title" varchar,
  "body" text,
  "user_id" integer NOT NULL,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "Arcadia"."Locations" (
  "locationId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(45)",
  "streetAddress" "VARCHAR(45)",
  "city" "VARCHAR(45)",
  "state" "VARCHAR(45)",
  "zip" "VARCHAR(45)"
);

CREATE TABLE "Arcadia"."Users" (
  "userId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "userName" "VARCHAR(45)",
  "password" "VARCHAR(255)"
);

CREATE TABLE "Arcadia"."Reviews" (
  "reviewId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "locationId" INT NOT NULL,
  "userId" INT NOT NULL,
  "rating" "DECIMAL(2,1)",
  "reviewText" "LONGTEXT"
);

CREATE TABLE "Arcadia"."Games" (
  "gameId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "gameName" "VARCHAR(45)",
  "gameGenre" "VARCHAR(45)",
  "gameYear" "VARCHAR(45)",
  "gameDescription" TEXT,
  "gameRegion" "VARCHAR(45)",
  "gamePlatform" "VARCHAR(45)",
  "gameSeries" "VARCHAR(255)",
  "gameManufacturer" "VARCHAR(45)",
  "gamePlayers" "VARCHAR(45)"
);

CREATE TABLE "Arcadia"."Gamelist" (
  "locationId" INT NOT NULL,
  "gameId" INT NOT NULL,
  PRIMARY KEY ("locationId", "gameId")
);

CREATE TABLE "Arcadia"."Users_Like_Locations" (
  "userId" INT NOT NULL,
  "locationId" INT NOT NULL,
  PRIMARY KEY ("userId", "locationId")
);

CREATE TABLE "Arcadia"."Users_Like_Games" (
  "userId" INT NOT NULL,
  "gameId" INT NOT NULL,
  PRIMARY KEY ("userId", "gameId")
);

CREATE INDEX "locationId_idx" ON "Arcadia"."Reviews" ("locationId");

CREATE INDEX "userId_idx" ON "Arcadia"."Reviews" ("userId");

CREATE INDEX "fk_Gamelist_Games1_idx" ON "Arcadia"."Gamelist" ("gameId");

CREATE INDEX "fk_Users_has_Locations_Locations1_idx" ON "Arcadia"."Users_Like_Locations" ("locationId");

CREATE INDEX "fk_Users_has_Locations_Users1_idx" ON "Arcadia"."Users_Like_Locations" ("userId");

CREATE INDEX "fk_Users_has_Games_Games1_idx" ON "Arcadia"."Users_Like_Games" ("gameId");

CREATE INDEX "fk_Users_has_Games_Users1_idx" ON "Arcadia"."Users_Like_Games" ("userId");

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

ALTER TABLE "posts" ADD CONSTRAINT "user_posts" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Reviews" ADD CONSTRAINT "fk_locationId" FOREIGN KEY ("locationId") REFERENCES "Arcadia"."Locations" ("locationId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Reviews" ADD CONSTRAINT "fk_userId" FOREIGN KEY ("userId") REFERENCES "Arcadia"."Users" ("userId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Gamelist" ADD CONSTRAINT "fk_Gamelist_Games1" FOREIGN KEY ("gameId") REFERENCES "Arcadia"."Games" ("gameId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Gamelist" ADD CONSTRAINT "fk_Gamelist_Locations1" FOREIGN KEY ("locationId") REFERENCES "Arcadia"."Locations" ("locationId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Users_Like_Locations" ADD CONSTRAINT "fk_Users_has_Locations_Users1" FOREIGN KEY ("userId") REFERENCES "Arcadia"."Users" ("userId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Users_Like_Locations" ADD CONSTRAINT "fk_Users_has_Locations_Locations1" FOREIGN KEY ("locationId") REFERENCES "Arcadia"."Locations" ("locationId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Users_Like_Games" ADD CONSTRAINT "fk_Users_has_Games_Users1" FOREIGN KEY ("userId") REFERENCES "Arcadia"."Users" ("userId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Arcadia"."Users_Like_Games" ADD CONSTRAINT "fk_Users_has_Games_Games1" FOREIGN KEY ("gameId") REFERENCES "Arcadia"."Games" ("gameId") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

-- Defer constraint checking for INSERT
BEGIN;
SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "users" ("id", "username", "role")
VALUES
  (0, 'Alice', 'admin'),
  (1, 'Bob', 'moderator'),
  (2, 'Candice', 'moderator'),
  (3, 'David', 'member');
INSERT INTO "follows" ("following_user_id", "followed_user_id", "created_at")
VALUES
  (1, 0, '2026-01-01'),
  (3, 2, '2026-02-28');
INSERT INTO "posts" ("id", "title", "user_id")
VALUES
  (0, 'Welcome to the forum!', 0),
  (1, 'Guidelines', 1),
  (2, 'Hello all!', 3);

SET CONSTRAINTS ALL IMMEDIATE;
COMMIT;