-- MySQL Script generated by MySQL Workbench
-- Wed May  6 11:51:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Arcadia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Arcadia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Arcadia` ;
USE `Arcadia` ;

-- -----------------------------------------------------
-- Table `Arcadia`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Locations` (
  `locationId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `streetAddress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  PRIMARY KEY (`locationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arcadia`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arcadia`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Reviews` (
  `reviewId` INT NOT NULL AUTO_INCREMENT,
  `locationId` INT NOT NULL,
  `userId` INT NOT NULL,
  `rating` DECIMAL(2,1) NULL,
  `reviewText` LONGTEXT NULL,
  PRIMARY KEY (`reviewId`),
  INDEX `locationId_idx` (`locationId` ASC) VISIBLE,
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_locationId`
    FOREIGN KEY (`locationId`)
    REFERENCES `Arcadia`.`Locations` (`locationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `Arcadia`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arcadia`.`Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Games` (
  `gameId` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(45) NULL,
  `gameGenre` VARCHAR(45) NULL,
  `gameDescription` TEXT NULL,
  PRIMARY KEY (`gameId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arcadia`.`Gamelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Gamelist` (
  `locationId` INT NOT NULL,
  `gameId` INT NOT NULL,
  PRIMARY KEY (`locationId`, `gameId`),
  INDEX `fk_Gamelist_Games1_idx` (`gameId` ASC) VISIBLE,
  CONSTRAINT `fk_Gamelist_Games1`
    FOREIGN KEY (`gameId`)
    REFERENCES `Arcadia`.`Games` (`gameId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gamelist_Locations1`
    FOREIGN KEY (`locationId`)
    REFERENCES `Arcadia`.`Locations` (`locationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arcadia`.`Users_Like_Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Users_Like_Locations` (
  `userId` INT NOT NULL,
  `locationId` INT NOT NULL,
  PRIMARY KEY (`userId`, `locationId`),
  INDEX `fk_Users_has_Locations_Locations1_idx` (`locationId` ASC) VISIBLE,
  INDEX `fk_Users_has_Locations_Users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Locations_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `Arcadia`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Locations_Locations1`
    FOREIGN KEY (`locationId`)
    REFERENCES `Arcadia`.`Locations` (`locationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arcadia`.`Users_Like_Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Arcadia`.`Users_Like_Games` (
  `userId` INT NOT NULL,
  `gameId` INT NOT NULL,
  PRIMARY KEY (`userId`, `gameId`),
  INDEX `fk_Users_has_Games_Games1_idx` (`gameId` ASC) VISIBLE,
  INDEX `fk_Users_has_Games_Users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Games_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `Arcadia`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Games_Games1`
    FOREIGN KEY (`gameId`)
    REFERENCES `Arcadia`.`Games` (`gameId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
