-- =============================================================================
-- Arcadia — initial schema for Supabase / Postgres
--
-- Paste the entire contents of this file into the Supabase SQL Editor
-- (Database → SQL Editor → New query) and run it.
--
-- Notes on naming:
--   This migration uses snake_case for tables and columns (Postgres convention).
--   Mapping from your Workbench diagram:
--     Users                  → profiles            (extends auth.users)
--     Locations              → locations
--     Games                  → games
--     Reviews                → reviews
--     Gamelist               → gamelist
--     Users_Like_Locations   → user_liked_locations
--     Users_Like_Games       → user_liked_games
--   Camel-case columns (userId, locationId, …) become snake_case (user_id, …).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Tables
-- -----------------------------------------------------------------------------

-- profiles: per-user app data, 1:1 with auth.users.
-- Created automatically by the trigger below when a new auth user signs up.
CREATE TABLE public.profiles (
  user_id   uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name varchar(45)
);

CREATE TABLE public.locations (
  location_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           varchar(45),
  street_address varchar(45),
  city           varchar(45),
  state          varchar(45),
  zip            varchar(45)
);

CREATE TABLE public.games (
  game_id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name        varchar(45),
  game_genre       varchar(45),
  game_description text
);

CREATE TABLE public.reviews (
  review_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id int NOT NULL REFERENCES public.locations(location_id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  rating      decimal(2,1),
  review_text text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reviews_location_id_idx ON public.reviews (location_id);
CREATE INDEX reviews_user_id_idx     ON public.reviews (user_id);

-- M:N: which games are at which arcade.
CREATE TABLE public.gamelist (
  location_id int NOT NULL REFERENCES public.locations(location_id) ON DELETE CASCADE,
  game_id     int NOT NULL REFERENCES public.games(game_id) ON DELETE CASCADE,
  PRIMARY KEY (location_id, game_id)
);
CREATE INDEX gamelist_game_id_idx ON public.gamelist (game_id);

-- M:N: locations a user has liked.
CREATE TABLE public.user_liked_locations (
  user_id     uuid NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  location_id int NOT NULL REFERENCES public.locations(location_id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, location_id)
);
CREATE INDEX user_liked_locations_location_id_idx ON public.user_liked_locations (location_id);

-- M:N: games a user has liked.
CREATE TABLE public.user_liked_games (
  user_id uuid NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  game_id int NOT NULL REFERENCES public.games(game_id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, game_id)
);
CREATE INDEX user_liked_games_game_id_idx ON public.user_liked_games (game_id);


-- -----------------------------------------------------------------------------
-- 2. Auto-create a profile when a new auth user signs up
--
-- SECURITY DEFINER lets the trigger insert into public.profiles even though
-- RLS is enabled and the inserting role wouldn't otherwise have permission.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (user_id, user_name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'user_name', NEW.email)
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- -----------------------------------------------------------------------------
-- 3. Row-Level Security
--
-- RLS is OFF by default on a fresh table. Without enabling it, the anon
-- (publishable) key would have full read/write access. Enable it on every
-- table, then add policies to grant back the access you actually want.
--
-- Convention used here:
--   - Public-facing data (locations, games, reviews) is world-readable.
--   - Writes require an authenticated session.
--   - Reviews and likes can only be modified by the user that owns them.
--   - Likes are private (only the owner sees them). Relax to public read by
--     changing `USING (auth.uid() = user_id)` to `USING (true)` on the SELECT
--     policies if you want a "people who like X" feature.
-- -----------------------------------------------------------------------------

ALTER TABLE public.profiles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gamelist             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_liked_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_liked_games     ENABLE ROW LEVEL SECURITY;


-- profiles: anyone can read, owner can update their own row.
-- (No INSERT policy — the trigger inserts as SECURITY DEFINER.
--  No DELETE policy — profiles are removed by cascade from auth.users.)
CREATE POLICY profiles_select_all ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- locations: public read, authenticated write.
CREATE POLICY locations_select_all ON public.locations
  FOR SELECT USING (true);

CREATE POLICY locations_insert_authed ON public.locations
  FOR INSERT TO authenticated WITH CHECK (true);


-- games: public read, authenticated write.
CREATE POLICY games_select_all ON public.games
  FOR SELECT USING (true);

CREATE POLICY games_insert_authed ON public.games
  FOR INSERT TO authenticated WITH CHECK (true);


-- reviews: public read, authenticated users manage their own reviews only.
CREATE POLICY reviews_select_all ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY reviews_insert_own ON public.reviews
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY reviews_update_own ON public.reviews
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY reviews_delete_own ON public.reviews
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);


-- gamelist: public read, authenticated write.
-- Tighten to admin-only later if you don't want every signed-in user adding games.
CREATE POLICY gamelist_select_all ON public.gamelist
  FOR SELECT USING (true);

CREATE POLICY gamelist_insert_authed ON public.gamelist
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY gamelist_delete_authed ON public.gamelist
  FOR DELETE TO authenticated USING (true);


-- user_liked_locations: private — owner-only read and write.
CREATE POLICY user_liked_locations_select_own ON public.user_liked_locations
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY user_liked_locations_insert_own ON public.user_liked_locations
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY user_liked_locations_delete_own ON public.user_liked_locations
  FOR DELETE TO authenticated USING (auth.uid() = user_id);


-- user_liked_games: private — owner-only read and write.
CREATE POLICY user_liked_games_select_own ON public.user_liked_games
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY user_liked_games_insert_own ON public.user_liked_games
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY user_liked_games_delete_own ON public.user_liked_games
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
